"""Adds foreign key to messages

Revision ID: 9fb7c3823579
Revises: 97cabd721223
Create Date: 2026-06-26 23:47:19.476758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb7c3823579'
down_revision = '97cabd721223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'receivers', ['receiver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('receiver_id')

    # ### end Alembic commands ###
